M48
; DRILL file KiCad 10.0.1 date 2026-06-15T12:02:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-15T12:02:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X160.175Y-342.95
X160.2Y-69.95
X424.175Y-69.975
X424.175Y-342.9
M30
